// src/utils/tw.ts
export const tw = (classes: string): object => {
  const classMap: { [key: string]: object } = {
    // Layout
    'flex': { display: 'flex' },
    'flex-1': { flex: 1 },
    'flex-row': { flexDirection: 'row' },
    'flex-col': { flexDirection: 'column' },
    'flex-wrap': { flexWrap: 'wrap' },
    'flex-nowrap': { flexWrap: 'nowrap' },
    'items-start': { alignItems: 'flex-start' },
    'items-center': { alignItems: 'center' },
    'items-end': { alignItems: 'flex-end' },
    'justify-start': { justifyContent: 'flex-start' },
    'justify-center': { justifyContent: 'center' },
    'justify-end': { justifyContent: 'flex-end' },
    'justify-between': { justifyContent: 'space-between' },
    'justify-around': { justifyContent: 'space-around' },
    'justify-evenly': { justifyContent: 'space-evenly' },
    'grid': { display: 'grid' },
    'grid-cols-1': { gridTemplateColumns: 'repeat(1, minmax(0, 1fr))' },
    'grid-cols-2': { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' },
    'grid-cols-3': { gridTemplateColumns: 'repeat(3, minmax(0, 1fr))' },
    'gap-4': { gap: 16 },
    'gap-6': { gap: 24 },
    'gap-8': { gap: 32 },
    'absolute': { position: 'absolute' },
    'relative': { position: 'relative' },
    'fixed': { position: 'fixed' },
    'sticky': { position: 'sticky' },
    'top-0': { top: 0 },
    'bottom-0': { bottom: 0 },
    'left-0': { left: 0 },
    'right-0': { right: 0 },
    'bottom-24': { bottom: 96 },
    'right-6': { right: 24 },

    // Spacing (Padding)
    'top-16': { top: 64 },
    'p-1': { padding: 4 },
    'p-2': { padding: 8 },
    'p-3': { padding: 12 },
    'p-4': { padding: 16 },
    'p-6': { padding: 24 },
    'p-8': { padding: 32 },
    'px-1': { paddingLeft: 4, paddingRight: 4 },
    'px-2': { paddingLeft: 8, paddingRight: 8 },
    'px-4': { paddingLeft: 16, paddingRight: 16 },
    'px-6': { paddingLeft: 24, paddingRight: 24 },
    'py-1': { paddingTop: 4, paddingBottom: 4 },
    'py-2': { paddingTop: 8, paddingBottom: 8 },
    'py-3': { paddingTop: 12, paddingBottom: 12 },
    'py-4': { paddingTop: 16, paddingBottom: 16 },
    'py-8': { paddingTop: 32, paddingBottom: 32 },
    'pt-2': { paddingTop: 8 },
    'pt-4': { paddingTop: 16 },
    'pt-16': { paddingTop: 64 },
    'pb-2': { paddingBottom: 8 },
    'pb-4': { paddingBottom: 16 },
    'pb-6': { paddingBottom: 24 },
    'pl-2': { paddingLeft: 8 },
    'pr-2': { paddingRight: 8 },

    // Spacing (Margin)
    'm-1': { margin: 4 },
    'm-2': { margin: 8 },
    'm-3': { margin: 12 },
    'm-4': { margin: 16 },
    'm-6': { margin: 24 },
    'mx-1': { marginLeft: 4, marginRight: 4 },
    'mx-2': { marginLeft: 8, marginRight: 8 },
    'mx-4': { marginLeft: 16, marginRight: 16 },
    'my-1': { marginTop: 4, marginBottom: 4 },
    'my-2': { marginTop: 8, marginBottom: 8 },
    'my-4': { marginTop: 16, marginBottom: 16 },
    'mt-1': { marginTop: 4 },
    'mt-2': { marginTop: 8 },
    'mt-3': { marginTop: 12 },
    'mt-4': { marginTop: 16 },
    'mt-6': { marginTop: 24 },
    'mt-8': { marginTop: 32 },
    'mb-1': { marginBottom: 4 },
    'mb-2': { marginBottom: 8 },
    'mb-3': { marginBottom: 12 },
    'mb-4': { marginBottom: 16 },
    'mb-6': { marginBottom: 24 },
    'mb-8': { marginBottom: 32 },
    'mb-20': { marginBottom: 80 },
    'ml-1': { marginLeft: 4 },
    'ml-2': { marginLeft: 8 },
    'mr-1': { marginRight: 4 },
    'mr-2': { marginRight: 8 },
    'mr-3': { marginRight: 12 },

    // Colors (Background)
    'bg-transparent': { backgroundColor: 'transparent' },
    'bg-white': { backgroundColor: '#ffffff' },
    'bg-black': { backgroundColor: '#000000' },
    'bg-gray-50': { backgroundColor: '#f9fafb' },
    'bg-gray-100': { backgroundColor: '#f3f4f6' },
    'bg-gray-200': { backgroundColor: '#e5e7eb' },
    'bg-gray-300': { backgroundColor: '#d1d5db' },
    'bg-gray-400': { backgroundColor: '#9ca3af' },
    'bg-gray-500': { backgroundColor: '#6b7280' },
    'bg-gray-600': { backgroundColor: '#4b5563' },
    'bg-gray-700': { backgroundColor: '#374151' },
    'bg-gray-800': { backgroundColor: '#1f2937' },
    'bg-gray-900': { backgroundColor: '#111827' },
    'bg-blue-100': { backgroundColor: '#dbeafe' },
    'bg-blue-500': { backgroundColor: '#3b82f6' },
    'bg-blue-600': { backgroundColor: '#2563eb' },
    'bg-blue-700': { backgroundColor: '#1d4ed8' },
    'bg-red-100': { backgroundColor: '#fee2e2' },
    'bg-red-500': { backgroundColor: '#ef4444' },
    'bg-red-600': { backgroundColor: '#dc2626' },
    'bg-green-100': { backgroundColor: '#d1fae5' },
    'bg-green-500': { backgroundColor: '#10b981' },
    'bg-green-600': { backgroundColor: '#059669' },
    'bg-yellow-100': { backgroundColor: '#fef3c7' },
    'bg-yellow-500': { backgroundColor: '#f59e0b' },
    'bg-yellow-600': { backgroundColor: '#d97706' },
    'bg-primary-500': { backgroundColor: '#2563eb' },
    'bg-success-500': { backgroundColor: '#10b981' },
    'bg-error-500': { backgroundColor: '#ef4444' },

    // Colors (Text)
    'text-white': { color: '#ffffff' },
    'text-black': { color: '#000000' },
    'text-gray-100': { color: '#f3f4f6' },
    'text-gray-300': { color: '#d1d5db' },
    'text-gray-500': { color: '#6b7280' },
    'text-gray-700': { color: '#374151' },
    'text-gray-800': { color: '#1f2937' },
    'text-gray-900': { color: '#111827' },
    'text-blue-500': { color: '#3b82f6' },
    'text-blue-600': { color: '#2563eb' },
    'text-red-400': { color: '#f87171' },
    'text-red-500': { color: '#ef4444' },
    'text-red-600': { color: '#dc2626' },
    'text-green-500': { color: '#10b981' },
    'text-yellow-500': { color: '#f59e0b' },
    'text-primary-500': { color: '#2563eb' },
    'text-success-500': { color: '#10b981' },
    'text-error-500': { color: '#ef4444' },

    // Typography
    'text-xs': { fontSize: 12 },
    'text-sm': { fontSize: 14 },
    'text-base': { fontSize: 16 },
    'text-lg': { fontSize: 18 },
    'text-xl': { fontSize: 20 },
    'text-2xl': { fontSize: 24 },
    'text-3xl': { fontSize: 30 },
    'text-4xl': { fontSize: 36 },
    'font-light': { fontWeight: '300' },
    'font-normal': { fontWeight: '400' },
    'font-medium': { fontWeight: '500' },
    'font-semibold': { fontWeight: '600' },
    'font-bold': { fontWeight: '700' },
    'font-extrabold': { fontWeight: '800' },
    'text-center': { textAlign: 'center' },
    'text-left': { textAlign: 'left' },
    'text-right': { textAlign: 'right' },
    'leading-tight': { lineHeight: 1.25 },
    'leading-normal': { lineHeight: 1.5 },
    'leading-loose': { lineHeight: 2 },

    // Borders
    'border': { borderWidth: 1 },
    'border-2': { borderWidth: 2 },
    'border-b': { borderBottomWidth: 1 },
    'border-t': { borderTopWidth: 1 },
    'border-l': { borderLeftWidth: 1 },
    'border-r': { borderRightWidth: 1 },
    'border-gray-100': { borderColor: '#f3f4f6' },
    'border-gray-300': { borderColor: '#d1d5db' },
    'border-blue-500': { borderColor: '#3b82f6' },
    'border-red-500': { borderColor: '#ef4444' },
    'rounded': { borderRadius: 4 },
    'rounded-md': { borderRadius: 6 },
    'rounded-lg': { borderRadius: 8 },
    'rounded-xl': { borderRadius: 12 },
    'rounded-full': { borderRadius: 9999 },

    // Sizing
    'w-4': { width: 16 },
    'w-6': { width: 24 },
    'w-8': { width: 32 },
    'w-10': { width: 40 },
    'w-12': { width: 48 },
    'w-14': { width: 56 },
    'w-16': { width: 64 },
    'w-full': { width: '100%' },
    'h-4': { height: 16 },
    'h-6': { height: 24 },
    'h-8': { height: 32 },
    'h-10': { height: 40 },
    'h-12': { height: 48 },
    'h-14': { height: 56 },
    'h-16': { height: 64 },
    'h-full': { height: '100%' },
    'max-w-sm': { maxWidth: 384 },
    'max-w-md': { maxWidth: 448 },
    'max-w-lg': { maxWidth: 512 },

    // Shadows
    'shadow': {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 1.41,
      elevation: 2,
    },
    'shadow-md': {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.23,
      shadowRadius: 2.62,
      elevation: 4,
    },
    'shadow-lg': {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    'shadow-xl': {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 4.65,
      elevation: 7,
    },

    // Opacity
    'opacity-50': { opacity: 0.5 },
    'opacity-75': { opacity: 0.75 },
    'opacity-100': { opacity: 1 },

    // Transitions
    'transition': { transitionProperty: 'all', transitionDuration: '150ms', transitionTimingFunction: 'ease-in-out' },
    'duration-300': { transitionDuration: '300ms' },
    'ease-in': { transitionTimingFunction: 'ease-in' },
    'ease-out': { transitionTimingFunction: 'ease-out' },

    // Visibility
    'hidden': { display: 'none' },
    'block': { display: 'block' },
    'inline-block': { display: 'inline-block' },
    'inline': { display: 'inline' },
  };

  return classes.split(' ').reduce((styles, className) => ({
    ...styles,
    ...classMap[className],
  }), {});
};